eureka:
  client:
    register-with-eureka: false
server:
  port: 8022

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: registry
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/regestry/**
        - id: Show
          uri: http://localhost:8075
          predicates:
            - Path=/api/v1/shows/**
  application:
    name: gateway
