eureka:
  instance:
    hostname: false

  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
server:
  port: 8075
spring:
  application:
    name: show
  data:
    mongodb:
      database: ms2020
      host: localhost
      port: 27017